### PR TITLE
Update from dev branch

### PR DESCRIPTION
**Pull request by gaohoward**
Signed-off-by: Howard Gao <howard.gao@gmail.com>

Thanks for submitting your Pull Request!

Please make sure your PR meets the following requirements:

- [ ] Pull Request title is properly formatted: `[CLOUD-XYA] Subject`
- [ ] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket
- [ ] Attached commits represent units of work and are properly formatted
- [ ] You have read and agreed to the Developer Certificate of Origin (DCO) (see `CONTRIBUTING.md`)
- [ ] Every commit contains `Signed-off-by: Your Name <yourname@example.com>` - use `git commit -s`

### CODE REVIEW

**Comment by gaohoward** [comment]
@stanlyDoge Hi Stan can you review this pls?
Thanks.

**Review by sknot-rh — APPROVED** [review]
LGTM

**Comment by goldmann** [comment]
I'm not sure what's the purpose of this PR since the version `1.4` was not released yet. https://access.redhat.com/containers/#/registry.access.redhat.com/jboss-amq-6/amq63-openshift For me it's wrong.

**Comment by gaohoward** [comment]
Hi @goldmann, does that mean I don't need to rebuild the image for now? If so should I revert this merge? Sorry if I ask stupid questions.

Howard

**Pull request merged**
